name: test20240305
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: post issue coment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let env
            if ("${{ inputs.environment }}" == 'dev') {
              env = "dev1";
            } else {
              env = "stg1";
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: env
            })
            
